#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
ASTRONOMICAL TEMPORAL SLIDING-WINDOW STACKING & STABILIZATION ENGINE (SIRIL CLI)
================================================================================
Processes high-cadence astronomical timelapses (e.g. 1 frame/sec) with target
output cadence (e.g. 6 sec/frame, Convention-over-Configuration 'i1_o6').

Pipeline Steps:
  1. Temporal Sliding Window: Extracts 12-frame overlapping sliding temporal
     windows (5 previous, 1 center, 6 next) with temporal stride of 6 frames.
  2. Intra-Window Subpixel Registration: Aligns the 12 input frames in each
     window to the central reference frame using Hanning-apodized FFT phase
     correlation and Lanczos-4 subpixel interpolation.
  3. Parallel Siril CLI Stacking: Executes professional astronomical Winsorized
     Sigma Clipping rejection stacking in parallel across isolated workers.
  4. Post-Siril Subpixel Stabilization: Fits exact lunar disk center via Huber
     loss Nelder-Mead circle optimization and warps to canonical canvas center (640, 360)
     with subpixel Lanczos-4 interpolation.
  5. Temporal Luminance Deflicker: Eliminates frame-to-frame auto-exposure jumps
     and atmospheric transparency fluctuations via adaptive Gaussian curve equalisation.
  6. Broadcast Encoding: Renders clean H.264 master and split-screen QA video.

Outputs:
  - Master video: '040_out/<project>/<project>_<process_type>.mp4'
  - Preprocessed asset: '005_raw_preprocessed/<project>/<filename>'
  - Side-by-side QA video: '040_out/<project>/restored_comparison_<project>_<process_type>.mp4'
  - Diagnostic comparison stills in '040_out/<project>/'

Authors: Fernando (nandoide) & Antigravity (Google Deepmind)
Workspace: eclipse_assembler
================================================================================
"""

import os
import sys
import re
import time
import shutil
import argparse
import subprocess
import multiprocessing as mp
from typing import List, Tuple, Optional, Dict

import cv2
import numpy as np
from scipy.optimize import minimize
from scipy.ndimage import gaussian_filter1d
from tqdm import tqdm

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from project_manager import resolve_project, get_repo_root


def find_siril_cli() -> str:
    """
    Locates the Siril CLI executable on macOS or Linux.
    Searches standard installation paths and system PATH.
    """
    candidates = [
        "/Applications/Siril.app/Contents/MacOS/siril-cli",
        shutil.which("siril-cli"),
        shutil.which("siril"),
        "/usr/local/bin/siril-cli",
        "/opt/homebrew/bin/siril-cli",
        "/usr/bin/siril-cli",
    ]
    for c in candidates:
        if c and os.path.isfile(c) and os.access(c, os.X_OK):
            return os.path.abspath(c)
    raise FileNotFoundError(
        "Siril CLI ('siril-cli') executable could not be found. "
        "Please ensure Siril is installed in /Applications/Siril.app or available on system PATH."
    )


def parse_temporal_cadence(filename: str, default_i: float = 1.0, default_o: float = 6.0) -> Tuple[float, float, int, int]:
    """
    Extracts input and output temporal step from filename (e.g. '01_timelapse_i1_o6.mp4').
    
    Returns:
        (i_step_s, o_step_s, stride_frames, window_size_frames)
    """
    basename = os.path.basename(filename)
    name_no_ext, _ = os.path.splitext(basename)
    tokens = name_no_ext.split('_')

    i_step = default_i
    o_step = default_o

    for tok in tokens:
        tok_l = tok.lower()
        if tok_l.startswith("i") and tok_l[1:].replace('.', '', 1).isdigit():
            i_step = float(tok_l[1:])
        elif tok_l.startswith("o") and tok_l[1:].replace('.', '', 1).isdigit():
            o_step = float(tok_l[1:])

    stride = max(1, int(round(o_step / i_step)))
    window_size = 2 * stride

    return i_step, o_step, stride, window_size


def read_fits_image(fits_path: str, expected_shape: Tuple[int, int]) -> np.ndarray:
    """
    Reads a 32-bit float FITS file generated by Siril and converts to 8-bit BGR image.
    Handles FITS bottom-up vertical coordinate inversion and channel ordering (RGB -> BGR).
    """
    h, w = expected_shape
    with open(fits_path, 'rb') as f:
        while True:
            block = f.read(2880)
            if not block:
                raise ValueError(f"FITS header END not found in {fits_path}")
            if b'END ' in block:
                break
        data = np.fromfile(f, dtype='>f4')

    if len(data) == h * w * 3:
        data = data.reshape((3, h, w))
        # Siril 8-bit input stored as 0..255 inside 16-bit 0..65535 space => scale by 65535.0
        data_scaled = (data * 65535.0).clip(0, 255).astype(np.uint8)
        # FITS planes are [0]=R, [1]=G, [2]=B -> BGR is [2], [1], [0]
        bgr = cv2.merge([data_scaled[2], data_scaled[1], data_scaled[0]])
        # FITS is bottom-up, flip vertically to match standard image coordinates
        bgr = cv2.flip(bgr, 0)
        return bgr
    elif len(data) == h * w:
        data = data.reshape((h, w))
        data_scaled = (data * 65535.0).clip(0, 255).astype(np.uint8)
        gray = cv2.flip(data_scaled, 0)
        return cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
    else:
        raise ValueError(f"Unexpected FITS payload size: {len(data)} (expected {h*w*3} or {h*w})")


def process_siril_stack_task(task_args: Tuple) -> Tuple[int, np.ndarray, np.ndarray]:
    """
    Worker task: takes 12 frames, aligns them to center frame via Hanning phase correlation,
    saves to fully isolated scratch dir, runs Siril stack, and returns stacked BGR frame.
    """
    (
        window_idx,
        frames_batch,
        center_sub_idx,
        worker_dir,
        siril_bin,
        sigma_low,
        sigma_high,
        align_subpixel
    ) = task_args

    worker_dir = os.path.abspath(worker_dir)
    os.makedirs(worker_dir, exist_ok=True)
    num_frames = len(frames_batch)
    h, w, _ = frames_batch[0].shape

    # Intra-window subpixel alignment to center reference frame
    processed_frames = []
    if align_subpixel and num_frames > 1:
        ref_gray = cv2.cvtColor(frames_batch[center_sub_idx], cv2.COLOR_BGR2GRAY)
        hann = cv2.createHanningWindow((w, h), cv2.CV_32F)
        for i, f in enumerate(frames_batch):
            if i == center_sub_idx:
                processed_frames.append(f)
                continue
            gray = cv2.cvtColor(f, cv2.COLOR_BGR2GRAY)
            shift, _ = cv2.phaseCorrelate(np.float32(ref_gray), np.float32(gray), hann)
            # Warp target by -shift to bring into exact alignment with ref_gray
            M = np.float32([[1.0, 0.0, -shift[0]], [0.0, 1.0, -shift[1]]])
            aligned = cv2.warpAffine(f, M, (w, h), flags=cv2.INTER_LANCZOS4, borderMode=cv2.BORDER_REFLECT)
            processed_frames.append(aligned)
    else:
        processed_frames = frames_batch

    # Save PNG frames with 'raw_' prefix
    for i, frame in enumerate(processed_frames):
        img_name = f"raw_{i:02d}.png"
        cv2.imwrite(os.path.join(worker_dir, img_name), frame)

    # Prepare isolated config file for this worker
    dummy_ini = os.path.join(worker_dir, "siril.ini")
    with open(dummy_ini, "w", encoding="utf-8") as f:
        f.write("[core]\n")

    # Prepare Siril script (convert raw_ -out=. creates raw_00001.fit without name collision)
    script_content = (
        "requires 1.2.0\n"
        "convert raw_ -out=.\n"
        f"stack raw_ rej w {sigma_low:.1f} {sigma_high:.1f} -nonorm -out=stacked\n"
        "close\n"
    )
    script_path = os.path.join(worker_dir, "stack.ssf")
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    # Run Siril CLI with -o (offline) and -i (custom config) for total isolation
    cmd = [siril_bin, "-o", "-i", dummy_ini, "-d", worker_dir, "-s", script_path]
    try:
        res = subprocess.run(
            cmd,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=25.0
        )
    except subprocess.TimeoutExpired:
        pass

    fits_output = os.path.join(worker_dir, "stacked.fit")
    if not os.path.exists(fits_output):
        fits_output = os.path.join(worker_dir, "stacked.fits")

    if not os.path.exists(fits_output):
        # Fallback to simple mean if Siril failed
        stacked_bgr = np.mean([f.astype(np.float32) for f in processed_frames], axis=0).clip(0, 255).astype(np.uint8)
    else:
        try:
            stacked_bgr = read_fits_image(fits_output, (h, w))
        except Exception:
            stacked_bgr = np.mean([f.astype(np.float32) for f in processed_frames], axis=0).clip(0, 255).astype(np.uint8)

    # Clean up task directory completely
    shutil.rmtree(worker_dir, ignore_errors=True)

    raw_center_frame = frames_batch[center_sub_idx]
    return window_idx, stacked_bgr, raw_center_frame


def stabilize_and_deflicker_sequence(
    frames: List[np.ndarray],
    target_center: Tuple[float, float] = (640.0, 360.0),
    r_fixed: Optional[float] = None,
    deflicker_sigma: float = 15.0,
    enable_stabilization: bool = True,
    enable_deflicker: bool = True
) -> Tuple[List[np.ndarray], np.ndarray, np.ndarray]:
    """
    Applies high-precision subpixel astronomical stabilization and temporal deflickering
    to Siril stacked timelapse frames.
    """
    n = len(frames)
    if n == 0:
        return [], np.array([]), np.array([])
    
    h, w, _ = frames[0].shape
    t_cx, t_cy = target_center

    # 1. Determine or fit initial radius on central frame
    mid_idx = n // 2
    gray_mid = cv2.cvtColor(frames[mid_idx], cv2.COLOR_BGR2GRAY)
    th_val = max(10, min(60, int(0.20 * float(np.max(gray_mid)))))
    _, thresh = cv2.threshold(gray_mid, th_val, 255, cv2.THRESH_BINARY)
    cnts, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if cnts:
        cnt_mid = max(cnts, key=cv2.contourArea).reshape(-1, 2)
        (_, _), init_r = cv2.minEnclosingCircle(cnt_mid)
        radius = r_fixed or init_r
    else:
        radius = r_fixed or 230.0

    print(f"\n[STEP 3/4] Applying Subpixel Astronomical Stabilization & Deflicker (R={radius:.1f}px)...")

    centers = []
    lumas = []

    for i in tqdm(range(n), desc="Tracking Disk & Luminance", ncols=80):
        frame = frames[i]
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        max_v = float(np.max(gray))
        th_val = max(10, min(60, int(0.20 * max_v)))
        _, binary = cv2.threshold(gray, th_val, 255, cv2.THRESH_BINARY)
        contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        if contours:
            cnt = max(contours, key=cv2.contourArea).reshape(-1, 2)
            hull = cv2.convexHull(cnt).reshape(-1, 2)
            init_c = centers[-1] if centers else target_center
            def loss(c):
                cx, cy = c
                d = np.sqrt((hull[:, 0] - cx)**2 + (hull[:, 1] - cy)**2)
                err = np.abs(d - radius)
                return np.sum(np.where(err < 2.0, 0.5 * err**2, 2.0 * (err - 1.0)))
            opt = minimize(loss, [init_c[0], init_c[1]], method='Nelder-Mead', options={'xatol': 0.001, 'fatol': 0.01})
            centers.append((float(opt.x[0]), float(opt.x[1])))
        else:
            centers.append(centers[-1] if centers else target_center)

        mask = gray > 20
        lumas.append(float(np.mean(gray[mask])) if np.any(mask) else 100.0)

    centers = np.array(centers, dtype=np.float32)
    lumas = np.array(lumas, dtype=np.float32)

    smoothed_luma = gaussian_filter1d(lumas, sigma=deflicker_sigma) if enable_deflicker else lumas

    processed_frames = []
    for i in tqdm(range(n), desc="Warping & Deflickering", ncols=80):
        frame = frames[i]
        if enable_stabilization:
            cx, cy = centers[i]
            dx = t_cx - cx
            dy = t_cy - cy
            M = np.float32([[1.0, 0.0, dx], [0.0, 1.0, dy]])
            warped = cv2.warpAffine(
                frame, M, (w, h),
                flags=cv2.INTER_LANCZOS4,
                borderMode=cv2.BORDER_CONSTANT,
                borderValue=(0, 0, 0)
            )
        else:
            warped = frame.copy()

        if enable_deflicker and lumas[i] > 10.0 and smoothed_luma[i] > 10.0:
            gain = np.clip(smoothed_luma[i] / lumas[i], 0.60, 1.60)
            gray_w = cv2.cvtColor(warped, cv2.COLOR_BGR2GRAY)
            alpha = np.clip((gray_w.astype(np.float32) - 10.0) / 20.0, 0.0, 1.0)
            alpha_3 = np.dstack([alpha, alpha, alpha])
            corrected_moon = np.clip(warped.astype(np.float32) * gain, 0, 255)
            warped = (alpha_3 * corrected_moon + (1.0 - alpha_3) * warped.astype(np.float32)).astype(np.uint8)

        processed_frames.append(warped)

    return processed_frames, centers, lumas


def create_side_by_side_frame(
    raw_frame: np.ndarray,
    stacked_frame: np.ndarray,
    frame_idx: int,
    total_frames: int,
    elapsed_sec: float,
    i_step: float,
    o_step: float,
    window_size: int
) -> np.ndarray:
    """
    Constructs a dual-pane split-screen QA frame:
      Left: Raw decimated single frame (effective 6s interval)
      Right: Siril 12-frame Stacked + Subpixel Stabilized + Deflickered frame
    """
    h, w, c = raw_frame.shape
    combined = np.hstack([raw_frame, stacked_frame])
    comb_h, comb_w, _ = combined.shape

    mask_bg_left = (raw_frame[:, :, 0] < 8) & (raw_frame[:, :, 1] < 8) & (raw_frame[:, :, 2] < 8)
    mask_bg_right = (stacked_frame[:, :, 0] < 8) & (stacked_frame[:, :, 1] < 8) & (stacked_frame[:, :, 2] < 8)

    noise_l = np.std(raw_frame[mask_bg_left].astype(np.float32)) if np.any(mask_bg_left) else 0.0
    noise_r = np.std(stacked_frame[mask_bg_right].astype(np.float32)) if np.any(mask_bg_right) else 0.0

    # Top overlay banner
    overlay = combined.copy()
    cv2.rectangle(overlay, (0, 0), (comb_w, 64), (10, 10, 15), -1)
    cv2.rectangle(overlay, (0, comb_h - 44), (comb_w, comb_h), (10, 10, 15), -1)
    cv2.addWeighted(overlay, 0.75, combined, 0.25, 0, combined)

    # Dividing vertical line
    cv2.line(combined, (w, 0), (w, comb_h), (80, 80, 90), 2)

    font = cv2.FONT_HERSHEY_SIMPLEX
    # Left Header
    cv2.putText(combined, f"RAW DECIMATED (1 frame @ step {int(o_step)}s)", (24, 40), font, 0.85, (200, 200, 200), 2, cv2.LINE_AA)
    # Right Header
    cv2.putText(combined, f"SIRIL STACKED + STABILIZED ({window_size} frames @ step {int(o_step)}s)", (w + 24, 40), font, 0.80, (0, 220, 255), 2, cv2.LINE_AA)

    # Bottom Telemetry
    time_str = f"Time: +{int(elapsed_sec//60):02d}m {int(elapsed_sec%60):02d}s | Frame {frame_idx + 1:03d}/{total_frames:03d}"
    cv2.putText(combined, time_str, (24, comb_h - 15), font, 0.65, (220, 220, 220), 1, cv2.LINE_AA)

    snr_factor = noise_l / max(1e-4, noise_r) if noise_r > 0 else 1.0
    metric_str = f"Noise Std: {noise_r:.2f} (vs {noise_l:.2f} raw) | Noise Reduction: {snr_factor:.2f}x | Deflicker: ACTIVE"
    cv2.putText(combined, metric_str, (w + 24, comb_h - 15), font, 0.65, (0, 255, 180), 1, cv2.LINE_AA)

    return combined


def encode_video_ffmpeg(
    frames_list: List[np.ndarray],
    output_path: str,
    fps: float,
    width: int,
    height: int,
    desc: str = "Encoding Video"
):
    """
    Pipes raw BGR frames directly to ffmpeg to encode high-quality H.264 video.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    ffmpeg_cmd = [
        "ffmpeg", "-y",
        "-f", "rawvideo",
        "-vcodec", "rawvideo",
        "-s", f"{width}x{height}",
        "-pix_fmt", "bgr24",
        "-r", str(fps),
        "-i", "-",
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "16",
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        output_path
    ]

    proc = subprocess.Popen(ffmpeg_cmd, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
    for frame in tqdm(frames_list, desc=desc, ncols=80):
        proc.stdin.write(frame.tobytes())

    proc.stdin.close()
    proc.wait()
    if proc.returncode != 0:
        err = proc.stderr.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"FFmpeg encoding failed with exit code {proc.returncode}:\n{err}")


def run_stacked_timelapse_preprocessing(
    input_video: str,
    preprocessed_output_video: str,
    comparison_output_video: Optional[str] = None,
    sample_image_output: Optional[str] = None,
    i_step: Optional[float] = None,
    o_step: Optional[float] = None,
    sigma_low: float = 3.0,
    sigma_high: float = 3.0,
    align_subpixel_pre_siril: bool = True,
    enable_post_stabilization: bool = True,
    enable_post_deflicker: bool = True,
    deflicker_sigma: float = 15.0,
    target_center: Tuple[float, float] = (640.0, 360.0),
    num_workers: Optional[int] = None,
    temp_base_dir: Optional[str] = None
) -> Dict:
    """
    Main orchestration routine for temporal sliding-window Siril stacking,
    post-Siril subpixel optical stabilization, and temporal deflickering.
    """
    t_start = time.time()
    siril_bin = find_siril_cli()

    if not os.path.exists(input_video):
        raise FileNotFoundError(f"Input video not found: {input_video}")

    auto_i, auto_o, stride, window_size = parse_temporal_cadence(input_video)
    if i_step is not None:
        auto_i = i_step
    if o_step is not None:
        auto_o = o_step
        stride = max(1, int(round(auto_o / auto_i)))
        window_size = 2 * stride

    cap = cv2.VideoCapture(input_video)
    if not cap.isOpened():
        raise ValueError(f"Could not open input video: {input_video}")

    total_input_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    center_sub_idx = stride - 1  # For window=12 (stride=6), index 5 (6th frame)

    num_windows = (total_input_frames - window_size) // stride + 1
    if num_windows <= 0:
        raise ValueError(
            f"Input video has {total_input_frames} frames, but minimum required for window size {window_size} is {window_size} frames."
        )

    if num_workers is None:
        num_workers = max(1, min(mp.cpu_count(), 8))

    if temp_base_dir is None:
        repo_root = get_repo_root()
        temp_base_dir = os.path.join(repo_root, "scratch", "siril_workers")
    os.makedirs(temp_base_dir, exist_ok=True)

    print("=" * 72)
    print("ASTRONOMICAL TEMPORAL SLIDING-WINDOW STACKING & STABILIZATION (SIRIL)")
    print("=" * 72)
    print(f"  Input Video Source       : {input_video}")
    print(f"  Total Input Frames       : {total_input_frames} ({total_input_frames/fps:.2f}s @ {fps:.1f} fps)")
    print(f"  Input Cadence (i)        : {auto_i:.2f} s / frame")
    print(f"  Output Cadence (o)       : {auto_o:.2f} s / frame")
    print(f"  Temporal Stride (S)      : {stride} frames")
    print(f"  Window Size (W)          : {window_size} frames (5 prev + 1 center + 6 next)")
    print(f"  Output Stacked Frames    : {num_windows} frames ({num_windows/fps:.2f}s @ {fps:.1f} fps)")
    print(f"  Siril CLI Binary         : {siril_bin}")
    print(f"  Rejection Algorithm      : Winsorized Sigma Clipping ({sigma_low:.1f}, {sigma_high:.1f})")
    print(f"  Intra-Window Alignment   : {'ENABLED (Hanning Phase Correlation)' if align_subpixel_pre_siril else 'DISABLED'}")
    print(f"  Post-Siril Stabilization : {'ENABLED (Nelder-Mead Huber Center)' if enable_post_stabilization else 'DISABLED'}")
    print(f"  Temporal Deflickering    : {'ENABLED (Gaussian Sigma=' + str(deflicker_sigma) + ')' if enable_post_deflicker else 'DISABLED'}")
    print(f"  Parallel Workers         : {num_workers}")
    print("=" * 72)

    print("\n[STEP 1/4] Reading source video frames into memory buffer...")
    all_source_frames = []
    for _ in tqdm(range(total_input_frames), desc="Reading source video", ncols=80):
        ret, frame = cap.read()
        if not ret:
            break
        all_source_frames.append(frame)
    cap.release()

    tasks = []
    for k in range(num_windows):
        start_idx = k * stride
        window_frames = all_source_frames[start_idx : start_idx + window_size]
        task_dir = os.path.join(temp_base_dir, f"task_{k:04d}")
        task_args = (
            k,
            window_frames,
            center_sub_idx,
            task_dir,
            siril_bin,
            sigma_low,
            sigma_high,
            align_subpixel_pre_siril
        )
        tasks.append(task_args)

    print(f"\n[STEP 2/4] Executing {num_windows} Siril stacking jobs across {num_workers} parallel workers...")
    t_stack_start = time.time()
    
    stacked_results = {}
    raw_center_results = {}
    with mp.Pool(processes=num_workers) as pool:
        for w_idx, stacked_frame, raw_frame in tqdm(pool.imap_unordered(process_siril_stack_task, tasks), total=num_windows, desc="Siril Stacking", ncols=80):
            stacked_results[w_idx] = stacked_frame
            raw_center_results[w_idx] = raw_frame

    stack_duration = time.time() - t_stack_start
    print(f"  -> Finished {num_windows} Siril stacks in {stack_duration:.2f}s ({num_windows/max(0.1, stack_duration):.1f} frames/s)")

    ordered_stacked_frames = [stacked_results[i] for i in range(num_windows)]
    ordered_raw_frames = [raw_center_results[i] for i in range(num_windows)]

    del all_source_frames
    del stacked_results
    del raw_center_results

    # -------------------------------------------------------------------------
    # STEP 3: Post-Siril Subpixel Stabilization & Deflicker
    # -------------------------------------------------------------------------
    if enable_post_stabilization or enable_post_deflicker:
        final_stacked_frames, centers_arr, lumas_arr = stabilize_and_deflicker_sequence(
            frames=ordered_stacked_frames,
            target_center=target_center,
            deflicker_sigma=deflicker_sigma,
            enable_stabilization=enable_post_stabilization,
            enable_deflicker=enable_post_deflicker
        )
    else:
        final_stacked_frames = ordered_stacked_frames

    # -------------------------------------------------------------------------
    # STEP 4: Render Output Video & Diagnostics
    # -------------------------------------------------------------------------
    print("\n[STEP 4/4] Rendering preprocessed video and side-by-side QA video...")

    # 1. Master Output Video
    encode_video_ffmpeg(
        frames_list=final_stacked_frames,
        output_path=preprocessed_output_video,
        fps=fps,
        width=width,
        height=height,
        desc="Rendering Master Video"
    )

    # 2. Side-by-Side QA Comparison Video
    if comparison_output_video:
        side_by_side_frames = []
        for i in tqdm(range(num_windows), desc="Building QA Frames", ncols=80):
            elapsed_s = i * auto_o
            sbs = create_side_by_side_frame(
                raw_frame=ordered_raw_frames[i],
                stacked_frame=final_stacked_frames[i],
                frame_idx=i,
                total_frames=num_windows,
                elapsed_sec=elapsed_s,
                i_step=auto_i,
                o_step=auto_o,
                window_size=window_size
            )
            side_by_side_frames.append(sbs)

        encode_video_ffmpeg(
            frames_list=side_by_side_frames,
            output_path=comparison_output_video,
            fps=fps,
            width=width * 2,
            height=height,
            desc="Rendering QA Split-Screen Video"
        )
        del side_by_side_frames

    # 3. Save Sample Comparison Image (Midpoint Frame)
    if sample_image_output:
        mid_idx = num_windows // 2
        sample_img = create_side_by_side_frame(
            raw_frame=ordered_raw_frames[mid_idx],
            stacked_frame=final_stacked_frames[mid_idx],
            frame_idx=mid_idx,
            total_frames=num_windows,
            elapsed_sec=mid_idx * auto_o,
            i_step=auto_i,
            o_step=auto_o,
            window_size=window_size
        )
        os.makedirs(os.path.dirname(sample_image_output), exist_ok=True)
        cv2.imwrite(sample_image_output, sample_img)
        print(f"  • QA Sample Still Saved : {sample_image_output}")

    # Clean up worker base temp directory
    try:
        shutil.rmtree(temp_base_dir, ignore_errors=True)
    except OSError:
        pass

    total_time = time.time() - t_start
    print("\n" + "=" * 72)
    print(f"PIPELINE COMPLETED SUCCESSFULLY in {total_time:.2f}s")
    print("=" * 72)
    print(f"  • Master Output Video   : {preprocessed_output_video}")
    if comparison_output_video:
        print(f"  • Split-Screen QA Video : {comparison_output_video}")
    print("=" * 72)

    return {
        "num_stacked_frames": num_windows,
        "preprocessed_video": preprocessed_output_video,
        "comparison_video": comparison_output_video,
        "elapsed_seconds": total_time,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Astronomical Temporal Sliding-Window Stacking & Stabilization Pipeline with Siril CLI"
    )
    parser.add_argument(
        "--project", "-p",
        type=str,
        default="moon260828",
        help="Project directory name in 010_in/ (default: moon260828)"
    )
    parser.add_argument(
        "--input", "-i",
        type=str,
        default=None,
        help="Custom input video path (overrides project discovery)"
    )
    parser.add_argument(
        "--out", "-o",
        type=str,
        default=None,
        help="Custom preprocessed output video path"
    )
    parser.add_argument(
        "--comp-out", "-c",
        type=str,
        default=None,
        help="Custom side-by-side QA video path"
    )
    parser.add_argument(
        "--i-step",
        type=float,
        default=None,
        help="Input capture interval in seconds (default: auto-detected from filename or 1.0s)"
    )
    parser.add_argument(
        "--o-step",
        type=float,
        default=None,
        help="Output target interval in seconds (default: auto-detected from filename or 6.0s)"
    )
    parser.add_argument(
        "--sigma-low",
        type=float,
        default=3.0,
        help="Winsorized sigma clipping lower threshold (default: 3.0)"
    )
    parser.add_argument(
        "--sigma-high",
        type=float,
        default=3.0,
        help="Winsorized sigma clipping higher threshold (default: 3.0)"
    )
    parser.add_argument(
        "--no-pre-align",
        action="store_true",
        default=False,
        help="Disable intra-window FFT subpixel pre-alignment before Siril stacking (default: False, pre-alignment enabled)"
    )
    parser.add_argument(
        "--no-stabilize",
        action="store_true",
        default=False,
        help="Disable post-Siril subpixel lunar disk stabilization (default: False)"
    )
    parser.add_argument(
        "--no-deflicker",
        action="store_true",
        default=False,
        help="Disable post-Siril temporal luminance deflickering (default: False)"
    )
    parser.add_argument(
        "--deflicker-sigma",
        type=float,
        default=15.0,
        help="Gaussian sigma for deflickering moving average (default: 15.0 frames)"
    )
    parser.add_argument(
        "--workers", "-w",
        type=int,
        default=None,
        help="Number of concurrent worker processes (default: CPU cores, max 8)"
    )
    parser.add_argument(
        "--process-type", "--style",
        type=str,
        default="standard",
        help="Process type identifier for output naming (default: standard)"
    )
    parser.add_argument(
        "--save-prep-asset",
        action="store_true",
        default=True,
        help="Also write preprocessed asset to 005_raw_preprocessed/ (default: True)"
    )

    args = parser.parse_args()
    repo_root = get_repo_root()

    if args.input:
        input_video = os.path.abspath(args.input)
        proj_name = "custom"
        prep_dir = os.path.join(repo_root, "005_raw_preprocessed", proj_name)
        out_dir = os.path.join(repo_root, "040_out", proj_name)
    else:
        proj = resolve_project(args.project, repo_root=repo_root)
        proj_name = proj["name"]
        prep_dir = os.path.join(repo_root, "005_raw_preprocessed", proj_name)
        out_dir = os.path.join(repo_root, "040_out", proj_name)

        in_dir = proj["in_dir"]
        timelapse_candidates = [
            os.path.join(in_dir, f)
            for f in os.listdir(in_dir)
            if f.endswith(".mp4") and ("timelapse" in f.lower() or "_i" in f.lower())
        ]
        if not timelapse_candidates:
            timelapse_candidates = [
                os.path.join(in_dir, f) for f in os.listdir(in_dir) if f.endswith(".mp4")
            ]
        if not timelapse_candidates:
            raise FileNotFoundError(f"No video files found in project input folder: {in_dir}")

        input_video = timelapse_candidates[0]

    os.makedirs(prep_dir, exist_ok=True)
    os.makedirs(out_dir, exist_ok=True)

    input_basename = os.path.basename(input_video)
    process_type = args.process_type
    out_master_name = f"{proj_name}_{process_type}.mp4"
    preprocessed_output_video = args.out or os.path.join(out_dir, out_master_name)
    comparison_output_video = args.comp_out or os.path.join(out_dir, f"restored_comparison_{proj_name}_{process_type}.mp4")
    sample_image_output = os.path.join(out_dir, f"sample_comparison_{proj_name}_{process_type}.jpg")

    result = run_stacked_timelapse_preprocessing(
        input_video=input_video,
        preprocessed_output_video=preprocessed_output_video,
        comparison_output_video=comparison_output_video,
        sample_image_output=sample_image_output,
        i_step=args.i_step,
        o_step=args.o_step,
        sigma_low=args.sigma_low,
        sigma_high=args.sigma_high,
        align_subpixel_pre_siril=not args.no_pre_align,
        enable_post_stabilization=not args.no_stabilize,
        enable_post_deflicker=not args.no_deflicker,
        deflicker_sigma=args.deflicker_sigma,
        num_workers=args.workers
    )

    if args.save_prep_asset:
        prep_asset_path = os.path.join(prep_dir, input_basename)
        if os.path.abspath(prep_asset_path) != os.path.abspath(preprocessed_output_video):
            shutil.copyfile(preprocessed_output_video, prep_asset_path)
            print(f"  • Preprocessed Asset Saved  : {prep_asset_path}")


if __name__ == "__main__":
    main()
